sonar.projectKey=EasyShop
sonar.projectName=EasyShop
sonar.sources=src
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.test.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
