apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "***REMOVED-JWT-SECRET***"
  NEXTAUTH_SECRET: "***REMOVED-NEXTAUTH-SECRET***"