apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      automountServiceAccountToken: false
      containers:
      - name: migration
        image: ishu11/e-shop-migration:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: easyshop-secrets
              key: MONGODB_URI
        - name: CDN_URL
          valueFrom:
            configMapKeyRef:
              name: easyshop-config
              key: CDN_URL
      restartPolicy: OnFailure
