apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter
  namespace: easyshop
  labels:
    release: argocd-monitoring
spec:
  selector:
    matchLabels:
      app: mongodb
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: easyshop
  labels:
    release: argocd-monitoring
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
